import { Config } from "effect"

function env(...keys: string[]) {
  return keys
    .map((key) => process.env[key])
    .find((value): value is string => value !== undefined)
}

function truthy(...keys: string[]) {
  const value = env(...keys)?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(...keys: string[]) {
  const value = env(...keys)?.toLowerCase()
  return value === "false" || value === "0"
}

function number(...keys: string[]) {
  const value = env(...keys)
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

function configBoolean(key: string) {
  return Config.boolean(key).pipe(Config.withDefault(false))
}

const FLASHCODE_EXPERIMENTAL = truthy("FLASHCODE_EXPERIMENTAL")
const FLASHCODE_DISABLE_CLAUDE_CODE = truthy("FLASHCODE_DISABLE_CLAUDE_CODE")
const FLASHCODE_DISABLE_CLAUDE_CODE_SKILLS =
  FLASHCODE_DISABLE_CLAUDE_CODE || truthy("FLASHCODE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = env("FLASHCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  FLASHCODE_AUTO_SHARE: truthy("FLASHCODE_AUTO_SHARE"),
  FLASHCODE_AUTO_HEAP_SNAPSHOT: truthy("FLASHCODE_AUTO_HEAP_SNAPSHOT"),
  FLASHCODE_GIT_BASH_PATH: env("FLASHCODE_GIT_BASH_PATH"),
  FLASHCODE_CONFIG: env("FLASHCODE_CONFIG"),
  FLASHCODE_CONFIG_CONTENT: env("FLASHCODE_CONFIG_CONTENT"),
  FLASHCODE_DISABLE_AUTOUPDATE: truthy("FLASHCODE_DISABLE_AUTOUPDATE"),
  FLASHCODE_ALWAYS_NOTIFY_UPDATE: truthy("FLASHCODE_ALWAYS_NOTIFY_UPDATE"),
  FLASHCODE_DISABLE_PRUNE: truthy("FLASHCODE_DISABLE_PRUNE"),
  FLASHCODE_DISABLE_TERMINAL_TITLE: truthy("FLASHCODE_DISABLE_TERMINAL_TITLE"),
  FLASHCODE_SHOW_TTFD: truthy("FLASHCODE_SHOW_TTFD"),
  FLASHCODE_PERMISSION: env("FLASHCODE_PERMISSION"),
  FLASHCODE_DISABLE_DEFAULT_PLUGINS: truthy("FLASHCODE_DISABLE_DEFAULT_PLUGINS"),
  FLASHCODE_DISABLE_LSP_DOWNLOAD: truthy("FLASHCODE_DISABLE_LSP_DOWNLOAD"),
  FLASHCODE_ENABLE_EXPERIMENTAL_MODELS: truthy("FLASHCODE_ENABLE_EXPERIMENTAL_MODELS"),
  FLASHCODE_DISABLE_AUTOCOMPACT: truthy("FLASHCODE_DISABLE_AUTOCOMPACT"),
  FLASHCODE_DISABLE_MODELS_FETCH: truthy("FLASHCODE_DISABLE_MODELS_FETCH"),
  FLASHCODE_DISABLE_MOUSE: truthy("FLASHCODE_DISABLE_MOUSE"),
  FLASHCODE_DISABLE_CLAUDE_CODE,
  FLASHCODE_DISABLE_CLAUDE_CODE_PROMPT: FLASHCODE_DISABLE_CLAUDE_CODE || truthy("FLASHCODE_DISABLE_CLAUDE_CODE_PROMPT"),
  FLASHCODE_DISABLE_CLAUDE_CODE_SKILLS,
  FLASHCODE_DISABLE_EXTERNAL_SKILLS: truthy("FLASHCODE_DISABLE_EXTERNAL_SKILLS"),
  FLASHCODE_FAKE_VCS: env("FLASHCODE_FAKE_VCS"),
  FLASHCODE_SERVER_PASSWORD: env("FLASHCODE_SERVER_PASSWORD"),
  FLASHCODE_SERVER_USERNAME: env("FLASHCODE_SERVER_USERNAME"),
  FLASHCODE_ENABLE_QUESTION_TOOL: truthy("FLASHCODE_ENABLE_QUESTION_TOOL"),

  // Experimental
  FLASHCODE_EXPERIMENTAL,
  FLASHCODE_EXPERIMENTAL_FILEWATCHER: configBoolean("FLASHCODE_EXPERIMENTAL_FILEWATCHER"),
  FLASHCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: configBoolean("FLASHCODE_EXPERIMENTAL_DISABLE_FILEWATCHER"),
  FLASHCODE_EXPERIMENTAL_ICON_DISCOVERY: FLASHCODE_EXPERIMENTAL || truthy("FLASHCODE_EXPERIMENTAL_ICON_DISCOVERY"),
  FLASHCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("FLASHCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  FLASHCODE_ENABLE_EXA:
    truthy("FLASHCODE_ENABLE_EXA") || FLASHCODE_EXPERIMENTAL || truthy("FLASHCODE_EXPERIMENTAL_EXA"),
  FLASHCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("FLASHCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  FLASHCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("FLASHCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  FLASHCODE_EXPERIMENTAL_OXFMT: FLASHCODE_EXPERIMENTAL || truthy("FLASHCODE_EXPERIMENTAL_OXFMT"),
  FLASHCODE_EXPERIMENTAL_LSP_TY: truthy("FLASHCODE_EXPERIMENTAL_LSP_TY"),
  FLASHCODE_EXPERIMENTAL_LSP_TOOL: FLASHCODE_EXPERIMENTAL || truthy("FLASHCODE_EXPERIMENTAL_LSP_TOOL"),
  FLASHCODE_EXPERIMENTAL_PLAN_MODE: FLASHCODE_EXPERIMENTAL || truthy("FLASHCODE_EXPERIMENTAL_PLAN_MODE"),
  FLASHCODE_EXPERIMENTAL_SCOUT: FLASHCODE_EXPERIMENTAL || truthy("FLASHCODE_EXPERIMENTAL_SCOUT"),
  FLASHCODE_EXPERIMENTAL_MARKDOWN: !falsy("FLASHCODE_EXPERIMENTAL_MARKDOWN"),
  FLASHCODE_ENABLE_PARALLEL:
    truthy("FLASHCODE_ENABLE_PARALLEL") || truthy("FLASHCODE_EXPERIMENTAL_PARALLEL"),
  FLASHCODE_MODELS_URL: env("FLASHCODE_MODELS_URL"),
  FLASHCODE_MODELS_PATH: env("FLASHCODE_MODELS_PATH"),
  FLASHCODE_DISABLE_EMBEDDED_WEB_UI: truthy("FLASHCODE_DISABLE_EMBEDDED_WEB_UI"),
  FLASHCODE_DB: env("FLASHCODE_DB"),
  FLASHCODE_DISABLE_CHANNEL_DB: truthy("FLASHCODE_DISABLE_CHANNEL_DB"),
  FLASHCODE_SKIP_MIGRATIONS: truthy("FLASHCODE_SKIP_MIGRATIONS"),
  FLASHCODE_STRICT_CONFIG_DEPS: truthy("FLASHCODE_STRICT_CONFIG_DEPS"),

  FLASHCODE_WORKSPACE_ID: env("FLASHCODE_WORKSPACE_ID"),
  FLASHCODE_EXPERIMENTAL_WORKSPACES:
    FLASHCODE_EXPERIMENTAL || truthy("FLASHCODE_EXPERIMENTAL_WORKSPACES"),
  FLASHCODE_EXPERIMENTAL_EVENT_SYSTEM:
    FLASHCODE_EXPERIMENTAL || truthy("FLASHCODE_EXPERIMENTAL_EVENT_SYSTEM"),
  FLASHCODE_EXPERIMENTAL_SESSION_SWITCHING: FLASHCODE_EXPERIMENTAL || truthy("FLASHCODE_EXPERIMENTAL_SESSION_SWITCHING"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get FLASHCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("FLASHCODE_DISABLE_PROJECT_CONFIG")
  },
  get FLASHCODE_TUI_CONFIG() {
    return env("FLASHCODE_TUI_CONFIG")
  },
  get FLASHCODE_CONFIG_DIR() {
    return env("FLASHCODE_CONFIG_DIR")
  },
  get FLASHCODE_EMBEDDED_CONFIG_DIR() {
    return env("FLASHCODE_EMBEDDED_CONFIG_DIR")
  },
  get FLASHCODE_PURE() {
    return truthy("FLASHCODE_PURE")
  },
  get FLASHCODE_PLUGIN_META_FILE() {
    return env("FLASHCODE_PLUGIN_META_FILE")
  },
  get FLASHCODE_CLIENT() {
    return env("FLASHCODE_CLIENT") ?? "cli"
  },
}
