import { Config } from "effect"

function env(...keys: string[]) {
  return keys.map((key) => process.env[key]).find((value) => value !== undefined)
}

export function truthy(...keys: string[]) {
  const value = env(...keys)?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["OPENCODE_DISABLE_FFF"]

function enabledByExperimental(...keys: string[]) {
  return keys.every((key) => process.env[key] === undefined)
    ? truthy("OPENCODE_EXPERIMENTAL", "FLASHCODE_EXPERIMENTAL")
    : truthy(...keys)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENCODE_AUTO_HEAP_SNAPSHOT: truthy("OPENCODE_AUTO_HEAP_SNAPSHOT", "FLASHCODE_AUTO_HEAP_SNAPSHOT"),
  OPENCODE_GIT_BASH_PATH: env("OPENCODE_GIT_BASH_PATH", "FLASHCODE_GIT_BASH_PATH"),
  OPENCODE_CONFIG: env("OPENCODE_CONFIG", "FLASHCODE_CONFIG"),
  OPENCODE_CONFIG_CONTENT: env("OPENCODE_CONFIG_CONTENT", "FLASHCODE_CONFIG_CONTENT"),
  OPENCODE_DISABLE_AUTOUPDATE: truthy("OPENCODE_DISABLE_AUTOUPDATE"),
  OPENCODE_ALWAYS_NOTIFY_UPDATE: truthy("OPENCODE_ALWAYS_NOTIFY_UPDATE"),
  OPENCODE_DISABLE_PRUNE: truthy("OPENCODE_DISABLE_PRUNE", "FLASHCODE_DISABLE_PRUNE"),
  OPENCODE_DISABLE_TERMINAL_TITLE: truthy("OPENCODE_DISABLE_TERMINAL_TITLE"),
  OPENCODE_SHOW_TTFD: truthy("OPENCODE_SHOW_TTFD"),
  OPENCODE_DISABLE_AUTOCOMPACT: truthy("OPENCODE_DISABLE_AUTOCOMPACT", "FLASHCODE_DISABLE_AUTOCOMPACT"),
  OPENCODE_DISABLE_MODELS_FETCH: truthy("OPENCODE_DISABLE_MODELS_FETCH", "FLASHCODE_DISABLE_MODELS_FETCH"),
  OPENCODE_DISABLE_MOUSE: truthy("OPENCODE_DISABLE_MOUSE"),
  OPENCODE_FAKE_VCS: process.env["OPENCODE_FAKE_VCS"],
  OPENCODE_SERVER_PASSWORD: env("OPENCODE_SERVER_PASSWORD", "FLASHCODE_SERVER_PASSWORD"),
  OPENCODE_SERVER_USERNAME: env("OPENCODE_SERVER_USERNAME", "FLASHCODE_SERVER_USERNAME"),
  OPENCODE_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("OPENCODE_DISABLE_FFF"),

  // Experimental
  OPENCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENCODE_MODELS_URL: process.env["OPENCODE_MODELS_URL"],
  OPENCODE_MODELS_PATH: env("OPENCODE_MODELS_PATH", "FLASHCODE_MODELS_PATH"),
  OPENCODE_DB: env("OPENCODE_DB", "FLASHCODE_DB"),

  OPENCODE_WORKSPACE_ID: env("OPENCODE_WORKSPACE_ID", "FLASHCODE_WORKSPACE_ID"),
  OPENCODE_EXPERIMENTAL_WORKSPACES: enabledByExperimental(
    "OPENCODE_EXPERIMENTAL_WORKSPACES",
    "FLASHCODE_EXPERIMENTAL_WORKSPACES",
  ),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("OPENCODE_DISABLE_PROJECT_CONFIG", "FLASHCODE_DISABLE_PROJECT_CONFIG")
  },
  get OPENCODE_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("OPENCODE_EXPERIMENTAL_REFERENCES")
  },
  get OPENCODE_TUI_CONFIG() {
    return process.env["OPENCODE_TUI_CONFIG"]
  },
  get OPENCODE_CONFIG_DIR() {
    return env("OPENCODE_CONFIG_DIR", "FLASHCODE_CONFIG_DIR")
  },
  get OPENCODE_PURE() {
    return truthy("OPENCODE_PURE", "FLASHCODE_PURE")
  },
  get OPENCODE_PERMISSION() {
    return env("OPENCODE_PERMISSION", "FLASHCODE_PERMISSION")
  },
  get OPENCODE_PLUGIN_META_FILE() {
    return env("OPENCODE_PLUGIN_META_FILE", "FLASHCODE_PLUGIN_META_FILE")
  },
  get OPENCODE_CLIENT() {
    return env("OPENCODE_CLIENT", "FLASHCODE_CLIENT") ?? "cli"
  },

  FLASHCODE_AUTO_HEAP_SNAPSHOT: truthy("FLASHCODE_AUTO_HEAP_SNAPSHOT", "OPENCODE_AUTO_HEAP_SNAPSHOT"),
  FLASHCODE_GIT_BASH_PATH: env("FLASHCODE_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH"),
  FLASHCODE_CONFIG: env("FLASHCODE_CONFIG", "OPENCODE_CONFIG"),
  FLASHCODE_CONFIG_CONTENT: env("FLASHCODE_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT"),
  FLASHCODE_DISABLE_PRUNE: truthy("FLASHCODE_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE"),
  FLASHCODE_DISABLE_AUTOCOMPACT: truthy("FLASHCODE_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT"),
  FLASHCODE_DISABLE_MODELS_FETCH: truthy("FLASHCODE_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH"),
  FLASHCODE_SERVER_PASSWORD: env("FLASHCODE_SERVER_PASSWORD", "OPENCODE_SERVER_PASSWORD"),
  FLASHCODE_SERVER_USERNAME: env("FLASHCODE_SERVER_USERNAME", "OPENCODE_SERVER_USERNAME"),
  FLASHCODE_ENABLE_EXPERIMENTAL_MODELS: truthy(
    "FLASHCODE_ENABLE_EXPERIMENTAL_MODELS",
    "OPENCODE_ENABLE_EXPERIMENTAL_MODELS",
  ),
  FLASHCODE_ENABLE_EXA: truthy("FLASHCODE_ENABLE_EXA", "OPENCODE_ENABLE_EXA", "FLASHCODE_EXPERIMENTAL_EXA"),
  FLASHCODE_ENABLE_PARALLEL: truthy(
    "FLASHCODE_ENABLE_PARALLEL",
    "OPENCODE_ENABLE_PARALLEL",
    "FLASHCODE_EXPERIMENTAL_PARALLEL",
  ),
  FLASHCODE_ENABLE_QUESTION_TOOL: truthy("FLASHCODE_ENABLE_QUESTION_TOOL", "OPENCODE_ENABLE_QUESTION_TOOL"),
  FLASHCODE_EXPERIMENTAL_LSP_TOOL: truthy("FLASHCODE_EXPERIMENTAL_LSP_TOOL", "OPENCODE_EXPERIMENTAL_LSP_TOOL"),
  FLASHCODE_EXPERIMENTAL_PLAN_MODE: truthy("FLASHCODE_EXPERIMENTAL_PLAN_MODE", "OPENCODE_EXPERIMENTAL_PLAN_MODE"),
  FLASHCODE_EXPERIMENTAL_SCOUT: truthy("FLASHCODE_EXPERIMENTAL_SCOUT", "OPENCODE_EXPERIMENTAL_SCOUT"),
  FLASHCODE_EXPERIMENTAL_WORKSPACES: enabledByExperimental(
    "FLASHCODE_EXPERIMENTAL_WORKSPACES",
    "OPENCODE_EXPERIMENTAL_WORKSPACES",
  ),
  FLASHCODE_MODELS_PATH: env("FLASHCODE_MODELS_PATH", "OPENCODE_MODELS_PATH"),
  FLASHCODE_DB: env("FLASHCODE_DB", "OPENCODE_DB"),
  FLASHCODE_WORKSPACE_ID: env("FLASHCODE_WORKSPACE_ID", "OPENCODE_WORKSPACE_ID"),
  get FLASHCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("FLASHCODE_DISABLE_PROJECT_CONFIG", "OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  get FLASHCODE_CONFIG_DIR() {
    return env("FLASHCODE_CONFIG_DIR", "OPENCODE_CONFIG_DIR")
  },
  get FLASHCODE_EMBEDDED_CONFIG_DIR() {
    return env("FLASHCODE_EMBEDDED_CONFIG_DIR", "OPENCODE_EMBEDDED_CONFIG_DIR")
  },
  get FLASHCODE_PURE() {
    return truthy("FLASHCODE_PURE", "OPENCODE_PURE")
  },
  get FLASHCODE_PERMISSION() {
    return env("FLASHCODE_PERMISSION", "OPENCODE_PERMISSION")
  },
  get FLASHCODE_PLUGIN_META_FILE() {
    return env("FLASHCODE_PLUGIN_META_FILE", "OPENCODE_PLUGIN_META_FILE")
  },
  get FLASHCODE_CLIENT() {
    return env("FLASHCODE_CLIENT", "OPENCODE_CLIENT") ?? "cli"
  },
}
